graph TD;
    Computer science-->Glossary of computer science;
    Computer science-->Computer science in sport;
    Computer science-->Critical code studies;
    Computer science-->Information and computer science;
    A-->B;
    Legendrian knot-->Thurston–Bennequin number;
